# 🔹 Основные настройки
split = "train"  # "train", "dev", "test"

# 🔹 Пути к данным
base_dir = "E:\\MELD"
csv_path = "{base_dir}\\MELD.Raw\\meld_{split}_labels.csv"
wav_dir = "{base_dir}\\wavs\\{split}"
video_dir = "{base_dir}\\MELD.Raw\\{split}_splits"

# 🔹 Датасет
modalities = ["audio"]
emotion_columns = ["neutral", "happy", "sad", "anger", "surprise", "disgust", "fear"]

# 🔹 DataLoader
[dataloader]
batch_size = 1
num_workers = 0
shuffle = true

# 🔹 Аудио параметры
[audio]
sample_rate = 16000
wav_length = 2

[audio_saving]
save_processed_audio = false  # true - сохранять обрезанные файлы, false - не сохранять
audio_output_dir = "{base_dir}\\output_wavs"   # Папка для сохранения обработанных файлов

# 🔹 Обработка текста
[text]
source = "csv"  # Для dev/test можно использовать "csv", train - всегда whisper
text_column = "text"  # Колонка с текстом в CSV (если source = "csv")
whisper_model = "tiny"  # Whisper model: "tiny", "base", "small", "medium", "large"
max_tokens = 5  # Максимальное количество слов в транскрипции
